[workspace]
resolver = "3"
members = [
    "pam",
    "gui",
    "kernel",
    "kcm",
    "kcm/face-id-kernel",
    "kcm/face-recognition-api",
    "kcm/face-id-kernel/migration", 
    "xtask"
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.104"
thiserror = "2.0.21"
dirs = "7.0.0"
jiff = "0.2.37"
fern = { version = "0.7.1", features = ["colored"] }
log = "0.4.34"
image = "0.25.10"
