use std::{
    fs,
    io::Write,
    path::{self, Path, PathBuf},
};

use anyhow::Context;
use cxx_qt_build::{CppFile, QResource, QResources};
use qt_build_utils::QResourceFile;

/// Recursively collect all .qml files under `dir`
fn collect_qml_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let mut entries: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|err| panic!("Cannot read directory {}: {err}", dir.display()))
        .map(|entry| entry.expect("Cannot read directory entry").path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            collect_qml_files(&path, out);
        } else if path.extension().is_some_and(|ext| ext == "qml") {
            out.push(path);
        }
    }
}

/// The directory cxx-qt-build exports the QML module to, mirroring its own
/// lookup: $CXX_QT_EXPORT_DIR or <target>/cxxqt, plus a "qml_modules" suffix.
fn qml_modules_export_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("CXX_QT_EXPORT_DIR") {
        return PathBuf::from(dir).join("qml_modules");
    }
    let target_dir = std::env::var("CARGO_TARGET_DIR").map(PathBuf::from).unwrap_or_else(|_| {
        // Walk up from OUT_DIR (= <target>/debug/build/<crate>-<hash>/out) to the
        // target directory, the same way cxx-qt-build detects it.
        let out_dir = PathBuf::from(
            std::env::var("OUT_DIR").expect("env 'OUT_DIR' not found"),
        );
        let mut dir = out_dir.clone();
        while dir.pop() {
            if dir.join(".rustc_info.json").exists()
                || dir.join("CACHEDIR.TAG").exists()
                || dir.file_name().is_some_and(|name| name == "target")
                    && dir.parent().is_some_and(|parent| parent.join("Cargo.toml").exists())
            {
                return dir;
            }
        }
        panic!("Could not locate the cargo target directory from {}", out_dir.display());
    });
    target_dir.join("cxxqt").join("qml_modules")
}

/// Write kcm/.qmlls.ini before cxx-qt-build runs, since cxx-qt-build only
/// generates the file when it does not exist.
///
/// The generated file is unusable here for two reasons: its paths are written
/// with Rust's `{:?}` escaping, which turns non-ASCII path segments (this repo
/// lives under ~/桌面) into `\u{...}` sequences that Qt's QSettings cannot
/// parse, and it lacks the `importPaths` entry that qmlls needs to resolve
/// `org.kde.linuxhello` without CMake build information.
fn ensure_qmlls_ini() {
    let ini_path = Path::new(&std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .join(".qmlls.ini");
    let modules_dir = qml_modules_export_dir();
    let contents = format!(
        "[General]\nbuildDir=\"{dir}\"\nno-cmake-calls=true\nimportPaths=\"{dir},/usr/lib/qt6/qml\"\n",
        dir = modules_dir.display(),
    );

    match fs::read_to_string(&ini_path) {
        // Repair a file previously generated by cxx-qt-build with escaped paths.
        Ok(existing) if existing.contains("\\u{") => {
            fs::write(&ini_path, contents).expect("Could not rewrite .qmlls.ini");
        }
        // Keep user customizations untouched.
        Ok(_) => {}
        Err(_) => {
            fs::write(&ini_path, contents).expect("Could not write .qmlls.ini");
        }
    }
}

fn main() -> anyhow::Result<()> {
    let include_dirs = kcm_include_dirs()?;

    // Watch the whole ui tree so that newly added QML files trigger a rescan.
    println!("cargo::rerun-if-changed=src/ui");

    ensure_qmlls_ini();

    let mut qml_files = Vec::new();
    collect_qml_files(Path::new("src/ui"), &mut qml_files);

    let mut builder = cxx_qt_build::CxxQtBuilder::new_qml_module(
        cxx_qt_build::QmlModule::new("org.kde.linuxhello").qml_files(qml_files),
    )
    .file("src/lib.rs")
    .cpp_file(CppFile::from("src/kcm_plugin.h").moc_arguments({
        let mut args = cxx_qt_build::MocArguments::default();
        args = args.include_paths(include_dirs.iter());
        args
    }))
    // The KCM framework loads the entry point from
    // qrc:/kcm/<kcm_name>/main.qml (see metadata.json), which is outside
    // the module's own qrc prefix, so expose main.qml under that URL.
    .qrc_resources(QResources::new().resource(
        QResource::new()
            .prefix("/kcm/kcm_linuxhello")
            .file(QResourceFile::new("src/ui/main.qml").alias("main.qml")),
    ));

    unsafe {
        builder = builder.cc_builder(|cc| {
            cc.flag_if_supported("-Wno-sfinae-incomplete");
            include_dirs.iter().for_each(|dir| {
                let _ = cc.include(dir);
            });
        })
    }

    let version_script = get_version_script();

    let exports_path = get_exports_path()?;

    let mut exports_file = get_exports_file(&exports_path)?;

    for symbol in KCM_EXPORT_SYMBOLS {
        println!("cargo::rustc-link-arg=-Wl,--undefined={symbol}")
    }

    exports_file.write_all(version_script.as_bytes())?;

    println!(
        "cargo::rustc-link-arg=-Wl,--version-script={}",
        exports_path.display()
    );

    builder.build();

    Ok(())
}

fn kf6_include_dirs() -> anyhow::Result<Vec<String>> {
    cmake_package::find_package("KF6KCMUtils")
        .find()
        .context("Couldn't find KF6KCMUtils, please install it")?
        .target("KF6::KCMUtilsQuick")
        .map(|target| {
            target.link();
            target.include_directories
        })
        .context("KF6::KCMUtilsQuick doesn't exist in KF6KCMUtils")
}

fn qt6_multimedia_include_dirs() -> anyhow::Result<Vec<String>> {
    cmake_package::find_package("Qt6Multimedia")
        .find()
        .context("Couldn't find Qt6Multimedia, please install it")?
        .target("Qt6::Multimedia")
        .map(|target| {
            target.link();
            target.include_directories
        })
        .context("Qt6::Multimedia doesn't exist in Qt6Multimedia")
}

fn qt6_concurrent_include_dirs() -> anyhow::Result<Vec<String>> {
    cmake_package::find_package("Qt6")
        .components(&["Concurrent".to_owned()])
        .find()
        .context("Couldn't find Qt6 with Concurrent, please install it")?
        .target("Qt6::Concurrent")
        .map(|target| {
            target.link();
            target.include_directories
        })
        .context("Qt6::Concurrent doesn't exist in Qt6's Concurrent component")
}

fn kcm_include_dirs() -> anyhow::Result<Vec<String>> {
    let mut kcm_dirs = kf6_include_dirs()?;
    let multimedia_dirs = qt6_multimedia_include_dirs()?;
    let concurrent_dirs = qt6_concurrent_include_dirs()?;
    kcm_dirs.extend_from_slice(&multimedia_dirs);
    kcm_dirs.extend_from_slice(&concurrent_dirs);
    Ok(kcm_dirs)
}

const KCM_EXPORT_SYMBOLS: &[&str] = &["qt_plugin_instance", "qt_plugin_query_metadata_v2"];

fn get_version_script() -> String {
    let mut version_script = r"{
    global:
"
    .to_owned();
    for symbol in KCM_EXPORT_SYMBOLS {
        version_script.push_str(&format!("\t\t{symbol};\n"));
    }
    version_script.push_str("};");
    version_script
}

fn get_exports_path() -> anyhow::Result<PathBuf> {
    Ok(
        path::Path::new(&std::env::var("OUT_DIR").context("env 'OUT_DIR' not found")?)
            .join("qt-plugin-exports.txt"),
    )
}

fn get_exports_file(exports_path: &path::Path) -> anyhow::Result<fs::File> {
    fs::OpenOptions::new()
        .write(true)
        .truncate(true)
        .create(true)
        .open(exports_path)
        .context("cannot open and write qt-plugin-exports.txt")
}
