[package]
name = "kcm"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
image.workspace = true
cxx = "1.0.202"
cxx-qt = "0.10.0"
cxx-kde-frameworks = { git = "https://invent.kde.org/libraries/cxx-kde-frameworks.git" }
dirs.workspace = true
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
thiserror.workspace = true
anyhow.workspace = true
cxx-qt-lib = "0.10.0"
jiff.workspace = true
fern.workspace = true
log.workspace = true
udev = "0.9.3"
face-recognition-api = { version = "0.1.0", path = "face-recognition-api" }
face-id-kernel = { version = "0.1.0", path = "face-id-kernel", optional = true }

[build-dependencies]
cmake-package = "0.2.0"
cxx-qt-build = "0.10.0"
anyhow.workspace = true

[features]
default = ["noop-kernel"]
noop-kernel = []
face-id-kernel = ["dep:face-id-kernel"]
test = []
