//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "faces")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Blob")]
    pub embedding: Vec<u8>,
    #[sea_orm(column_type = "Float")]
    pub norm: f32,
    pub created_at: DateTime,
}

impl ActiveModelBehavior for ActiveModel {}
